#!/bin/bash

# if not running interactively, don't do anything
[[ $- != *i* ]] && return

export COLORTERM=truecolor
export TERM=xterm-256color

# global bashrc
[ -f /etc/bashrc ] && . /etc/bashrc

# --- .bashrd.d ---

for file in ~/.bashrc.d/*; do
    . "$file"
done
